# TODO: Validate
[project]
name = "app"
version = "0.1.0"
description = ""
requires-python = ">=3.14,<4.0"
dependencies = [
  "alembic<2.0.0,>=1.12.1",
  "beautifulsoup4>=4.14.3",
  "chirashi",
  "deforestation",
  "diving-board",
  "email-validator<3.0.0.0,>=2.1.0.post1",
  "emails<1.0,>=0.6",
  "fastapi[standard]<0.129.0,>=0.128.0",
  "httpx<1.0.0,>=0.25.1",
  "jinja2<4.0.0,>=3.1.4",
  "just-scrape",
  "kneeminus",
  "loguru>=0.7.3",
  "lxml>=5.0.0",
  "meshfilm",
  "minbo",
  "nana",
  "naphki",
  "not-yt-dlapi",
  "notaplanet",
  "plugi",
  "psycopg[binary]<4.0.0,>=3.1.13",
  "pwdlib[argon2,bcrypt]>=0.3.0",
  "pydantic>=2.11",
  "pydantic-settings<3.0.0,>=2.2.1",
  "pyinstrument>=5.1.2",
  "pyjwt<3.0.0,>=2.8.0",
  "pykakasi>=2.3.0",
  "python-multipart<1.0.0,>=0.0.27",
  "rapidfuzz>=3.14.5",
  "sentry-sdk[fastapi]>=2.0.0,<3.0.0",
  "sqlmodel<1.0.0,>=0.0.21",
  "tenacity<9.0.0,>=8.2.3",
  "tminidb",
  "trivial-minus",
  "wampi",
  "wholoo",
  "yt-dlapi",
]

[dependency-groups]
dev = [
  "coverage<8.0.0,>=7.4.3",
  "freezegun>=1.0.0",
  "mypy<2.0.0,>=1.8.0",
  "prek>=0.2.24,<1.0.0",
  "pytest<8.0.0,>=7.4.3",
  "pytest-socket>=0.7.0",
  "pytest-split>=0.11.0",
  "ruff<1.0.0,>=0.2.2",
  "ty>=0.0.25",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
# Block network access for plugin tests.
addopts = "--disable-socket --allow-hosts=127.0.0.1,::1,localhost -s"
norecursedirs = ["old_mess", ".*", "build", "dist", "*.egg", "node_modules", "venv", ".venv"]

[tool.coverage.run]
source = ["app"]
dynamic_context = "test_function"

[tool.coverage.report]
show_missing = true
sort = "-Cover"

[tool.coverage.html]
show_contexts = true

[tool.mypy]
strict = true
exclude = ["venv", ".venv", "alembic"]

[tool.ruff]
target-version = "py314"
exclude = ["alembic"]

[tool.ruff.lint]
select = ["ALL", "D400", "D401", "D404"]
ignore = [
  # Ignores from the original template
  "E501",  # line too long, handled by black
  "B008",  # do not perform function calls in argument defaults
  "W191",  # indentation contains tabs
  "B904",  # Allow raising exceptions without from e, for HTTPException

  # Additional ignores.
  # Too many false positives.
  "TC001",
  "TC002",
  "TC003",

  # Allow all TODO comments
  "TD",
  "FIX002",

  "D",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]  # Asserts allowed in tests.

[tool.ty.terminal]
error-on-warning = true

[tool.uv.sources]
diving-board = { git = "https://github.com/ryn-cx/diving-board" }
chirashi = { git = "https://github.com/ryn-cx/chirashi" }
deforestation = { git = "https://github.com/ryn-cx/deforestation" }
naphki = { git = "https://github.com/ryn-cx/naphki" }
not-yt-dlapi = { git = "https://github.com/ryn-cx/not-yt-dlapi" }
yt-dlapi = { git = "https://github.com/ryn-cx/yt-dlapi" }
meshfilm = { git = "https://github.com/ryn-cx/meshfilm" }
tminidb = { git = "https://github.com/ryn-cx/tminidb" }
wholoo = { git = "https://github.com/ryn-cx/wholoo" }
minbo = { git = "https://github.com/ryn-cx/minbo" }
kneeminus = { git = "https://github.com/ryn-cx/knee-minus" }
trivial-minus = { git = "https://github.com/ryn-cx/trivial-minus" }
nana = { git = "https://github.com/ryn-cx/nana" }
plugi = { git = "https://github.com/ryn-cx/plugi" }
notaplanet = { git = "https://github.com/ryn-cx/notaplanet" }
just-scrape = { git = "https://github.com/ryn-cx/just-scrape" }
wampi = { git = "https://github.com/ryn-cx/wampi" }
