// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_watches_import_watch_historySchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_watches-import_watch_history'
} as const;

export const ChannelEpisodesOutputSchema = {
    properties: {
        episodes: {
            items: {
                '$ref': '#/components/schemas/EpisodeWithExtrasOutput'
            },
            type: 'array',
            title: 'Episodes'
        },
        seasons: {
            additionalProperties: {
                '$ref': '#/components/schemas/SeasonOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Seasons'
        },
        shows: {
            additionalProperties: {
                '$ref': '#/components/schemas/ShowOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Shows'
        },
        sources: {
            additionalProperties: {
                '$ref': '#/components/schemas/SourceOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Sources'
        },
        plugins: {
            additionalProperties: {
                '$ref': '#/components/schemas/PluginOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Plugins'
        },
        channels: {
            additionalProperties: {
                '$ref': '#/components/schemas/ChannelOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Channels'
        }
    },
    type: 'object',
    required: ['episodes', 'seasons', 'shows', 'sources', 'plugins', 'channels'],
    title: 'ChannelEpisodesOutput'
} as const;

export const ChannelMediaFilterSchema = {
    properties: {
        sortBy: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Sortby',
            default: []
        },
        episodeOrdering: {
            type: 'boolean',
            title: 'Episodeordering',
            default: false
        },
        episodeInterleaving: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episodeinterleaving'
        },
        additionalChannels: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Additionalchannels',
            default: []
        },
        rotateShows: {
            type: 'boolean',
            title: 'Rotateshows',
            default: false
        },
        rotateShowsRandomly: {
            type: 'boolean',
            title: 'Rotateshowsrandomly',
            default: false
        },
        randomizeOnLastSort: {
            type: 'boolean',
            title: 'Randomizeonlastsort',
            default: false
        },
        randomSeed: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Randomseed'
        },
        hideWatched: {
            type: 'boolean',
            title: 'Hidewatched',
            default: false
        },
        hideUnwatched: {
            type: 'boolean',
            title: 'Hideunwatched',
            default: false
        },
        maximumWatchDateAbsolute: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maximumwatchdateabsolute'
        },
        minimumAirDateAbsolute: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Minimumairdateabsolute'
        },
        maximumAirDateAbsolute: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maximumairdateabsolute'
        },
        minimumReleaseDateAbsolute: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Minimumreleasedateabsolute'
        },
        maximumReleaseDateAbsolute: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maximumreleasedateabsolute'
        },
        maximumWatchDateRelative: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maximumwatchdaterelative'
        },
        minimumAirDateRelative: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Minimumairdaterelative'
        },
        maximumAirDateRelative: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maximumairdaterelative'
        },
        minimumReleaseDateRelative: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Minimumreleasedaterelative'
        },
        maximumReleaseDateRelative: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maximumreleasedaterelative'
        },
        onlyStartedShows: {
            type: 'boolean',
            title: 'Onlystartedshows',
            default: false
        },
        onlyNewShows: {
            type: 'boolean',
            title: 'Onlynewshows',
            default: false
        },
        minimumDuration: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Minimumduration'
        },
        maximumDuration: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maximumduration'
        },
        limit: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        }
    },
    type: 'object',
    title: 'ChannelMediaFilter'
} as const;

export const ChannelOutputSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        channel_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Channel Number'
        },
        public: {
            type: 'boolean',
            title: 'Public',
            default: false
        },
        default_order: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Order'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['id', 'user_id'],
    title: 'ChannelOutput'
} as const;

export const ChannelPatchInputSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        channel_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Channel Number'
        },
        public: {
            type: 'boolean',
            title: 'Public',
            default: false
        },
        default_order: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Order'
        }
    },
    type: 'object',
    title: 'ChannelPatchInput'
} as const;

export const ChannelPostInputSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        channel_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Channel Number'
        },
        public: {
            type: 'boolean',
            title: 'Public',
            default: false
        },
        default_order: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Order'
        }
    },
    type: 'object',
    title: 'ChannelPostInput'
} as const;

export const ChannelQueueOutputSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        status: {
            '$ref': '#/components/schemas/URLStatus'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['url', 'status', 'id'],
    title: 'ChannelQueueOutput'
} as const;

export const ChannelQueuesListOutputSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChannelQueueOutput'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ChannelQueuesListOutput'
} as const;

export const ChannelShowsOutputSchema = {
    properties: {
        shows: {
            items: {
                '$ref': '#/components/schemas/ShowOutput'
            },
            type: 'array',
            title: 'Shows'
        },
        sources: {
            additionalProperties: {
                '$ref': '#/components/schemas/SourceOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Sources'
        }
    },
    type: 'object',
    title: 'ChannelShowsOutput'
} as const;

export const ChannelsListOutputSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ChannelOutput'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ChannelsListOutput'
} as const;

export const EpisodeOutputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        episode_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Number'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        duration: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration'
        },
        release_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Release Date'
        },
        air_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Air Date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        season_id: {
            type: 'string',
            format: 'uuid',
            title: 'Season Id'
        }
    },
    type: 'object',
    required: ['key', 'id', 'season_id'],
    title: 'EpisodeOutput'
} as const;

export const EpisodePatchInputSchema = {
    properties: {
        key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        episode_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Number'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        duration: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration'
        },
        release_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Release Date'
        },
        air_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Air Date'
        }
    },
    type: 'object',
    title: 'EpisodePatchInput'
} as const;

export const EpisodePostInputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        episode_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Number'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        duration: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration'
        },
        release_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Release Date'
        },
        air_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Air Date'
        }
    },
    type: 'object',
    title: 'EpisodePostInput'
} as const;

export const EpisodeWithExtrasOutputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        episode_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Number'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        duration: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration'
        },
        release_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Release Date'
        },
        air_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Air Date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        season_id: {
            type: 'string',
            format: 'uuid',
            title: 'Season Id'
        },
        watch_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Watch Date'
        },
        verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Verified'
        },
        episode_watch_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Episode Watch Id'
        },
        channel_id: {
            type: 'string',
            format: 'uuid',
            title: 'Channel Id'
        }
    },
    type: 'object',
    required: ['key', 'id', 'season_id', 'channel_id'],
    title: 'EpisodeWithExtrasOutput'
} as const;

export const EpisodesListOutputSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/EpisodeOutput'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'EpisodesListOutput'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MultipleSortOptionOutputsSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SortOptionOutput'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'MultipleSortOptionOutputs'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PluginOutputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        version: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        },
        public: {
            type: 'boolean',
            title: 'Public'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['key', 'public', 'id'],
    title: 'PluginOutput'
} as const;

export const PluginPatchInputSchema = {
    properties: {
        key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        version: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        },
        public: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public'
        }
    },
    type: 'object',
    title: 'PluginPatchInput'
} as const;

export const PluginPostInputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        version: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        },
        public: {
            type: 'boolean',
            title: 'Public'
        }
    },
    type: 'object',
    required: ['public'],
    title: 'PluginPostInput'
} as const;

export const PluginsListOutputSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PluginOutput'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'PluginsListOutput'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const SeasonOutputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        season_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Season Number'
        },
        show_id: {
            type: 'string',
            format: 'uuid',
            title: 'Show Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['key', 'show_id', 'id'],
    title: 'SeasonOutput'
} as const;

export const SeasonPatchInputSchema = {
    properties: {
        key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        season_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Season Number'
        }
    },
    type: 'object',
    title: 'SeasonPatchInput'
} as const;

export const SeasonPostInputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        season_number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Season Number'
        }
    },
    type: 'object',
    title: 'SeasonPostInput'
} as const;

export const SeasonsListOutputSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SeasonOutput'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'SeasonsListOutput'
} as const;

export const ShowOutputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        media_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        source_id: {
            type: 'string',
            format: 'uuid',
            title: 'Source Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['key', 'source_id', 'id'],
    title: 'ShowOutput'
} as const;

export const ShowPatchInputSchema = {
    properties: {
        key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        media_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    title: 'ShowPatchInput'
} as const;

export const ShowPostInputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        media_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    title: 'ShowPostInput'
} as const;

export const ShowsListOutputSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ShowOutput'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ShowsListOutput'
} as const;

export const SortOptionOutputSchema = {
    properties: {
        label: {
            type: 'string',
            title: 'Label'
        },
        value: {
            type: 'string',
            title: 'Value'
        }
    },
    type: 'object',
    required: ['label', 'value'],
    title: 'SortOptionOutput'
} as const;

export const SourceOutputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        favicon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Favicon Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        plugin_id: {
            type: 'string',
            format: 'uuid',
            title: 'Plugin Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['key', 'plugin_id', 'id'],
    title: 'SourceOutput'
} as const;

export const SourcePatchInputSchema = {
    properties: {
        key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        favicon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Favicon Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    title: 'SourcePatchInput'
} as const;

export const SourcePostInputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        favicon_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Favicon Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    title: 'SourcePostInput'
} as const;

export const SourcesListOutputSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SourceOutput'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'SourcesListOutput'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const URLStatusSchema = {
    type: 'string',
    enum: ['Pending', 'Failed', 'Imported', 'Importing'],
    title: 'URLStatus'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WatchImportFormatInformationSchema = {
    properties: {
        plugin_key: {
            type: 'string',
            title: 'Plugin Key'
        },
        file_type: {
            type: 'string',
            title: 'File Type'
        },
        file_extension: {
            type: 'string',
            title: 'File Extension'
        },
        instructions: {
            type: 'string',
            title: 'Instructions'
        }
    },
    type: 'object',
    required: ['plugin_key', 'file_type', 'file_extension', 'instructions'],
    title: 'WatchImportFormatInformation'
} as const;

export const WatchImportPluginsOutputSchema = {
    properties: {
        plugins: {
            items: {
                '$ref': '#/components/schemas/WatchImportFormatInformation'
            },
            type: 'array',
            title: 'Plugins'
        }
    },
    type: 'object',
    required: ['plugins'],
    title: 'WatchImportPluginsOutput'
} as const;

export const WatchImportResultSchema = {
    properties: {
        show: {
            type: 'string',
            title: 'Show'
        },
        show_url: {
            type: 'string',
            title: 'Show Url'
        },
        episode: {
            type: 'string',
            title: 'Episode'
        },
        episode_url: {
            type: 'string',
            title: 'Episode Url'
        }
    },
    type: 'object',
    required: ['show', 'show_url', 'episode', 'episode_url'],
    title: 'WatchImportResult'
} as const;

export const WatchImportResultsSchema = {
    properties: {
        added: {
            items: {
                '$ref': '#/components/schemas/WatchImportResult'
            },
            type: 'array',
            title: 'Added'
        },
        existing: {
            items: {
                '$ref': '#/components/schemas/WatchImportResult'
            },
            type: 'array',
            title: 'Existing'
        },
        skipped: {
            items: {
                '$ref': '#/components/schemas/WatchImportResult'
            },
            type: 'array',
            title: 'Skipped'
        }
    },
    type: 'object',
    required: ['added', 'existing', 'skipped'],
    title: 'WatchImportResults'
} as const;

export const WatchItemSchema = {
    properties: {
        watch_date: {
            type: 'string',
            format: 'date-time',
            title: 'Watch Date'
        },
        verified: {
            type: 'boolean',
            title: 'Verified'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        episode_id: {
            type: 'string',
            format: 'uuid',
            title: 'Episode Id'
        }
    },
    type: 'object',
    required: ['watch_date', 'verified', 'id', 'episode_id'],
    title: 'WatchItem'
} as const;

export const WatchOutputSchema = {
    properties: {
        watch_date: {
            type: 'string',
            format: 'date-time',
            title: 'Watch Date'
        },
        verified: {
            type: 'boolean',
            title: 'Verified'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        episode_id: {
            type: 'string',
            format: 'uuid',
            title: 'Episode Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['watch_date', 'verified', 'id', 'episode_id', 'user_id'],
    title: 'WatchOutput'
} as const;

export const WatchPatchInputSchema = {
    properties: {
        watch_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Watch Date'
        },
        verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Verified'
        }
    },
    type: 'object',
    title: 'WatchPatchInput'
} as const;

export const WatchPostInputSchema = {
    properties: {
        watch_date: {
            type: 'string',
            format: 'date-time',
            title: 'Watch Date'
        },
        verified: {
            type: 'boolean',
            title: 'Verified',
            default: false
        }
    },
    type: 'object',
    title: 'WatchPostInput'
} as const;

export const WatchesListOutputSchema = {
    properties: {
        watches: {
            items: {
                '$ref': '#/components/schemas/WatchItem'
            },
            type: 'array',
            title: 'Watches'
        },
        episodes: {
            additionalProperties: {
                '$ref': '#/components/schemas/EpisodeOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Episodes'
        },
        seasons: {
            additionalProperties: {
                '$ref': '#/components/schemas/SeasonOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Seasons'
        },
        shows: {
            additionalProperties: {
                '$ref': '#/components/schemas/ShowOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Shows'
        },
        sources: {
            additionalProperties: {
                '$ref': '#/components/schemas/SourceOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Sources'
        },
        plugins: {
            additionalProperties: {
                '$ref': '#/components/schemas/PluginOutput'
            },
            propertyNames: {
                format: 'uuid'
            },
            type: 'object',
            title: 'Plugins'
        }
    },
    type: 'object',
    required: ['watches', 'episodes', 'seasons', 'shows', 'sources', 'plugins'],
    title: 'WatchesListOutput'
} as const;

export const WhitelistEntryInputSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['id', 'enabled'],
    title: 'WhitelistEntryInput'
} as const;

export const WhitelistShowInputSchema = {
    properties: {
        whitelist_mode: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whitelist Mode'
        },
        seasons: {
            items: {
                '$ref': '#/components/schemas/WhitelistEntryInput'
            },
            type: 'array',
            title: 'Seasons',
            default: []
        },
        episodes: {
            items: {
                '$ref': '#/components/schemas/WhitelistEntryInput'
            },
            type: 'array',
            title: 'Episodes',
            default: []
        }
    },
    type: 'object',
    title: 'WhitelistShowInput'
} as const;

export const WhitelistShowOutputSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        data_timestamp: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Timestamp'
        },
        update_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Update At'
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        extra: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extra'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        media_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Type'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        source_id: {
            type: 'string',
            format: 'uuid',
            title: 'Source Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        whitelist_mode: {
            type: 'boolean',
            title: 'Whitelist Mode'
        },
        enabled_season_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Enabled Season Ids'
        },
        enabled_episode_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Enabled Episode Ids'
        },
        seasons: {
            items: {
                '$ref': '#/components/schemas/SeasonOutput'
            },
            type: 'array',
            title: 'Seasons'
        },
        episodes: {
            items: {
                '$ref': '#/components/schemas/EpisodeOutput'
            },
            type: 'array',
            title: 'Episodes'
        }
    },
    type: 'object',
    required: ['key', 'source_id', 'id', 'whitelist_mode', 'enabled_season_ids', 'enabled_episode_ids', 'seasons', 'episodes'],
    title: 'WhitelistShowOutput'
} as const;