// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChannelEpisodesOutput = {
    episodes: Array<EpisodeWithExtrasOutput>;
    seasons: {
        [key: string]: SeasonOutput;
    };
    shows: {
        [key: string]: ShowOutput;
    };
    sources: {
        [key: string]: SourceOutput;
    };
    plugins: {
        [key: string]: PluginOutput;
    };
    channels: {
        [key: string]: ChannelOutput;
    };
};

export type ChannelInput = {
    name: string;
    public?: boolean;
    default_order?: (string | null);
};

export type ChannelNameItem = {
    id: string;
    name: string;
};

export type ChannelNamesOutput = {
    data: Array<ChannelNameItem>;
};

export type ChannelOutput = {
    name: string;
    public?: boolean;
    default_order?: (string | null);
    id: string;
    user_id: string;
};

export type ChannelQueueOutput = {
    url: string;
    status: URLStatus;
    note?: (string | null);
    id: string;
};

export type ChannelShowsOutput = {
    shows?: Array<ShowOutput>;
    sources?: {
        [key: string]: SourceOutput;
    };
};

export type EpisodeOutput = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    url: string;
    sort_order?: number;
    description?: (string | null);
    image_url?: (string | null);
    episode_number?: (number | null);
    name?: (string | null);
    release_date?: (string | null);
    air_date?: (string | null);
    duration?: (number | null);
    season_id: string;
    id: string;
};

export type EpisodeWatchItem = {
    watch_date: string;
    verified: boolean;
    id: string;
    episode_id: string;
};

export type EpisodeWatchPatchInput = {
    watch_date: string;
    verified: boolean;
};

export type EpisodeWatchPostInput = {
    episode_id: string;
    watch_date: string;
    verified: boolean;
};

export type EpisodeWithExtrasOutput = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    url: string;
    sort_order?: number;
    description?: (string | null);
    image_url?: (string | null);
    episode_number?: (number | null);
    name?: (string | null);
    release_date?: (string | null);
    air_date?: (string | null);
    duration?: (number | null);
    season_id: string;
    id: string;
    watch_date?: (string | null);
    verified?: (boolean | null);
    episode_watch_id?: (string | null);
    channel_id: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type MultipleChannelOutputs = {
    data: Array<ChannelOutput>;
    count: number;
};

export type MultipleChannelQueueOutputs = {
    data: Array<ChannelQueueOutput>;
    count: number;
};

export type MultipleSortOptionOutputs = {
    data: Array<SortOptionOutput>;
    count: number;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PluginOutput = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name: string;
    id: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SeasonOutput = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    sort_order?: number;
    name?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
    season_number?: (number | null);
    show_id: string;
    id: string;
};

export type ShowOutput = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name: string;
    media_type?: (string | null);
    description?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
    source_id: string;
    id: string;
};

export type SingleEpisodeWatchOutput = {
    watch_date: string;
    verified?: boolean;
    id: string;
    episode: EpisodeOutput;
    season: SeasonOutput;
    show: ShowOutput;
    source: SourceOutput;
    plugin: PluginOutput;
};

export type SortOptionOutput = {
    label: string;
    value: string;
};

export type SourceOutput = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name: string;
    favicon_url?: (string | null);
    image_url?: (string | null);
    plugin_id: string;
    id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type URLStatus = 'Pending' | 'Failed' | 'Imported' | 'Importing';

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WatchedEpisodesOutput = {
    watches: Array<EpisodeWatchItem>;
    episodes: {
        [key: string]: EpisodeOutput;
    };
    seasons: {
        [key: string]: SeasonOutput;
    };
    shows: {
        [key: string]: ShowOutput;
    };
    sources: {
        [key: string]: SourceOutput;
    };
    plugins: {
        [key: string]: PluginOutput;
    };
    count: number;
};

export type WhitelistEpisodeInput = {
    id: string;
    enabled: boolean;
};

export type WhitelistSeasonInput = {
    id: string;
    enabled: boolean;
    episodes: Array<WhitelistEpisodeInput>;
};

export type WhitelistShowInput = {
    id: string;
    whitelist_mode: boolean;
    seasons: Array<WhitelistSeasonInput>;
};

export type WhitelistShowOutput = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name: string;
    media_type?: (string | null);
    description?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
    source_id: string;
    id: string;
    whitelist_mode: boolean;
    enabled_season_ids: Array<(string)>;
    enabled_episode_ids: Array<(string)>;
    seasons: Array<SeasonOutput>;
    episodes: Array<EpisodeOutput>;
};

export type WhitelistStatusOutput = {
    visible: boolean;
};

export type ChannelsGetSortOptionsResponse = (MultipleSortOptionOutputs);

export type ChannelsGetChannelsData = {
    limit?: number;
    skip?: number;
};

export type ChannelsGetChannelsResponse = (MultipleChannelOutputs);

export type ChannelsCreateChannelData = {
    requestBody: ChannelInput;
};

export type ChannelsCreateChannelResponse = (ChannelOutput);

export type ChannelsGetChannelNamesData = {
    channelIds: Array<(string)>;
};

export type ChannelsGetChannelNamesResponse = (ChannelNamesOutput);

export type ChannelsGetChannelData = {
    channelId: string;
};

export type ChannelsGetChannelResponse = (ChannelOutput);

export type ChannelsUpdateChannelData = {
    channelId: string;
    requestBody: ChannelInput;
};

export type ChannelsUpdateChannelResponse = (ChannelOutput);

export type ChannelsDeleteChannelData = {
    channelId: string;
};

export type ChannelsDeleteChannelResponse = (Message);

export type ChannelsAddUrlsToChannelImportQueueData = {
    channelId: string;
    requestBody: Array<(string)>;
};

export type ChannelsAddUrlsToChannelImportQueueResponse = (MultipleChannelQueueOutputs);

export type ChannelsGetChannelImportQueueData = {
    channelId: string;
    limit?: number;
    skip?: number;
};

export type ChannelsGetChannelImportQueueResponse = (MultipleChannelQueueOutputs);

export type ChannelsDeleteUrlFromChannelImportQueueData = {
    channelId: string;
    urlId: string;
};

export type ChannelsDeleteUrlFromChannelImportQueueResponse = (Message);

export type ChannelsClearCompletedChannelImportQueueData = {
    channelId: string;
};

export type ChannelsClearCompletedChannelImportQueueResponse = (Message);

export type ChannelsSetChannelShowWhitelistData = {
    channelId: string;
    requestBody: WhitelistShowInput;
    showId: string;
};

export type ChannelsSetChannelShowWhitelistResponse = (WhitelistShowOutput);

export type ChannelsGetChannelShowWhitelistData = {
    channelId: string;
    showId: string;
};

export type ChannelsGetChannelShowWhitelistResponse = (WhitelistShowOutput);

export type ChannelsSwapEpisodeWhitelistStatusData = {
    channelId: string;
    episodeId: string;
};

export type ChannelsSwapEpisodeWhitelistStatusResponse = (WhitelistStatusOutput);

export type ChannelsGetChannelShowsData = {
    channelId: string;
};

export type ChannelsGetChannelShowsResponse = (ChannelShowsOutput);

export type ChannelsGetChannelEpisodesData = {
    additionalChannels?: Array<(string)>;
    channelId: string;
    episodeInterleaving?: (string | null);
    episodeOrdering?: boolean;
    hideUnwatched?: boolean;
    hideWatched?: boolean;
    maximumAirDateAbsolute?: (string | null);
    maximumAirDateRelative?: (number | null);
    maximumDuration?: (number | null);
    maximumReleaseDateAbsolute?: (string | null);
    maximumReleaseDateRelative?: (number | null);
    maximumWatchDateAbsolute?: (string | null);
    maximumWatchDateRelative?: (number | null);
    minimumAirDateAbsolute?: (string | null);
    minimumAirDateRelative?: (number | null);
    minimumDuration?: (number | null);
    minimumReleaseDateAbsolute?: (string | null);
    minimumReleaseDateRelative?: (number | null);
    onlyNewShows?: boolean;
    onlyStartedShows?: boolean;
    randomizeOnLastSort?: boolean;
    rotateShows?: boolean;
    rotateShowsRandomly?: boolean;
    sortBy?: Array<(string)>;
};

export type ChannelsGetChannelEpisodesResponse = (ChannelEpisodesOutput);

export type ChannelsRemoveChannelShowData = {
    channelId: string;
    showId: string;
};

export type ChannelsRemoveChannelShowResponse = (Message);

export type ChannelsUpdateChannelDefaultOrderData = {
    additionalChannels?: Array<(string)>;
    channelId: string;
    episodeInterleaving?: (string | null);
    episodeOrdering?: boolean;
    hideUnwatched?: boolean;
    hideWatched?: boolean;
    maximumAirDateAbsolute?: (string | null);
    maximumAirDateRelative?: (number | null);
    maximumDuration?: (number | null);
    maximumReleaseDateAbsolute?: (string | null);
    maximumReleaseDateRelative?: (number | null);
    maximumWatchDateAbsolute?: (string | null);
    maximumWatchDateRelative?: (number | null);
    minimumAirDateAbsolute?: (string | null);
    minimumAirDateRelative?: (number | null);
    minimumDuration?: (number | null);
    minimumReleaseDateAbsolute?: (string | null);
    minimumReleaseDateRelative?: (number | null);
    onlyNewShows?: boolean;
    onlyStartedShows?: boolean;
    randomizeOnLastSort?: boolean;
    rotateShows?: boolean;
    rotateShowsRandomly?: boolean;
    sortBy?: Array<(string)>;
};

export type ChannelsUpdateChannelDefaultOrderResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaPostWatchedEpisodeData = {
    requestBody: EpisodeWatchPostInput;
};

export type MediaPostWatchedEpisodeResponse = (SingleEpisodeWatchOutput);

export type MediaGetWatchedEpisodesData = {
    limit?: number;
    skip?: number;
};

export type MediaGetWatchedEpisodesResponse = (WatchedEpisodesOutput);

export type MediaPatchWatchedEpisodeData = {
    episodeWatchId: string;
    requestBody: EpisodeWatchPatchInput;
};

export type MediaPatchWatchedEpisodeResponse = (SingleEpisodeWatchOutput);

export type MediaDeleteWatchedEpisodeData = {
    episodeWatchId: string;
};

export type MediaDeleteWatchedEpisodeResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);