// This file is auto-generated by @hey-api/openapi-ts

export type BlacklistEpisodeInput = {
    show_id: string;
    episode_id: string;
    expires_at?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_watches_import_watch_history = {
    file: (Blob | File);
};

/**
 * Schema for returning a `Channel` to an admin, including the owner username.
 */
export type ChannelAdminOutput = {
    name?: (string | null);
    channel_number?: (number | null);
    visibility: Visibility;
    default_order?: (string | null);
    description?: (string | null);
    anonymous?: boolean;
    id: string;
    user_id: (string | null);
    score: number;
    username: (string | null);
};

/**
 * Schema for an admin updating any field on a `Channel`.
 */
export type ChannelAdminUpdate = {
    name?: (string | null);
    channel_number?: (number | null);
    visibility?: (Visibility | null);
    default_order?: (string | null);
    description?: (string | null);
    anonymous?: boolean;
    score?: (number | null);
};

/**
 * Schema for creating a `Channel`.
 */
export type ChannelCreate = {
    name?: (string | null);
    channel_number?: (number | null);
    visibility: Visibility;
    default_order?: (string | null);
    description?: (string | null);
    anonymous?: boolean;
};

export type ChannelEpisodesOutput = {
    episodes: Array<EpisodeWithDetails>;
    seasons: {
        [key: string]: SeasonOutput;
    };
    shows: {
        [key: string]: ShowPublic;
    };
    sources: {
        [key: string]: SourcePublic;
    };
    plugins: {
        [key: string]: PluginOutput;
    };
    channels: {
        [key: string]: ChannelOutput;
    };
};

export type ChannelOptions = {
    sortBy?: Array<SortKeyInput>;
    additionalChannels?: Array<(string)>;
    sourceIds?: Array<(string)>;
    sourceIdsIsBlacklist?: boolean;
    randomSeed?: number;
    hideWatched?: boolean;
    hideUnwatched?: boolean;
    hidePartiallyWatched?: boolean;
    maximumWatchDateAbsolute?: (string | null);
    minimumAirDateAbsolute?: (string | null);
    maximumAirDateAbsolute?: (string | null);
    minimumReleaseDateAbsolute?: (string | null);
    maximumReleaseDateAbsolute?: (string | null);
    maximumWatchDateRelative?: (number | null);
    minimumAirDateRelative?: (number | null);
    maximumAirDateRelative?: (number | null);
    minimumReleaseDateRelative?: (number | null);
    maximumReleaseDateRelative?: (number | null);
    totalShowsCount?: (number | null);
    startedShowsCount?: (number | null);
    newShowsCount?: (number | null);
    minimumDuration?: (number | null);
    maximumDuration?: (number | null);
    limit?: (number | null);
};

/**
 * Schema for returning a `Channel`.
 */
export type ChannelOutput = {
    name?: (string | null);
    channel_number?: (number | null);
    visibility: Visibility;
    default_order?: (string | null);
    description?: (string | null);
    anonymous?: boolean;
    id: string;
    user_id: (string | null);
    score: number;
};

/**
 * Schema for returning a page of publicly listed `Channel`s.
 */
export type ChannelPublicListOutput = {
    data: Array<ChannelPublicOutput>;
    count: number;
};

/**
 * Schema for returning a publicly listed `Channel`.
 */
export type ChannelPublicOutput = {
    name?: (string | null);
    channel_number?: (number | null);
    visibility: Visibility;
    default_order?: (string | null);
    description?: (string | null);
    anonymous?: boolean;
    id: string;
    username: (string | null);
};

export type ChannelQueueOutput = {
    url: string;
    status: URLStatus;
    note?: (string | null);
    id: string;
    channel_id: string;
};

export type ChannelShowsOutput = {
    shows?: Array<ShowPublic>;
    filter_only_shows?: Array<ShowPublic>;
    sources?: {
        [key: string]: SourcePublic;
    };
};

/**
 * Schema for updating a `Channel`.
 */
export type ChannelUpdate = {
    name?: (string | null);
    channel_number?: (number | null);
    visibility?: (Visibility | null);
    default_order?: (string | null);
    description?: (string | null);
    anonymous?: boolean;
};

export type DateFilterOption = {
    id: string;
    value: DateRangeFilter;
};

export type DateRangeFilter = {
    minimumDate?: (string | null);
    maximumDate?: (string | null);
    hideBlanks?: boolean;
};

/**
 * Schema for creating an `Episode`.
 */
export type EpisodeCreate = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    url?: (string | null);
    sort_order?: (number | null);
    description?: (string | null);
    image_url?: (string | null);
    episode_number?: (number | null);
    name?: (string | null);
    duration?: (number | null);
    release_date?: (string | null);
    air_date?: (string | null);
};

/**
 * Schema for returning an `Episode`.
 */
export type EpisodeOutput = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    url?: (string | null);
    sort_order?: (number | null);
    description?: (string | null);
    image_url?: (string | null);
    episode_number?: (number | null);
    name?: (string | null);
    duration?: (number | null);
    release_date?: (string | null);
    air_date?: (string | null);
    id: string;
    season_id: string;
};

/**
 * Schema for returning a list of `Episode`s.
 */
export type EpisodesPublic = {
    data: Array<EpisodeOutput>;
    total_count: number;
    filtered_count: number;
    is_server_side: boolean;
};

/**
 * Schema for updating an `Episode`.
 */
export type EpisodeUpdate = {
    key?: (string | null);
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    url?: (string | null);
    sort_order?: (number | null);
    description?: (string | null);
    image_url?: (string | null);
    episode_number?: (number | null);
    name?: (string | null);
    duration?: (number | null);
    release_date?: (string | null);
    air_date?: (string | null);
};

export type EpisodeWithDetails = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    url?: (string | null);
    sort_order?: (number | null);
    description?: (string | null);
    image_url?: (string | null);
    episode_number?: (number | null);
    name?: (string | null);
    duration?: (number | null);
    release_date?: (string | null);
    air_date?: (string | null);
    id: string;
    season_id: string;
    watch_date?: (string | null);
    verified?: (boolean | null);
    episode_watch_id?: (string | null);
    channel_id: string;
    channel_ids?: Array<(string)>;
};

/**
 * Schema for creating a `File`.
 */
export type FileCreate = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    content?: (string | null);
};

/**
 * Schema for returning a list of `File`s, excluding `content`.
 *
 * `content` is excluded to reduce the response size.
 */
export type FileListPublic = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    plugin_id: string;
    id: string;
};

/**
 * Schema for returning a `File`.
 */
export type FilePublic = {
    key: string;
    data_timestamp: string;
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    content?: (string | null);
    plugin_id: string;
    id: string;
};

/**
 * Schema for updating a `File`.
 */
export type FileUpdate = {
    key?: (string | null);
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    content?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MediaOwner = 'official' | 'others';

/**
 * Generic message.
 */
export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Schema for creating a `Playlist`.
 */
export type PlaylistCreate = {
    name?: (string | null);
    visibility: Visibility;
    episode_ids?: Array<(string)>;
};

export type PlaylistDetailOutput = {
    name?: (string | null);
    visibility: Visibility;
    id: string;
    user_id: string;
    created_at: string;
    modified_at: string;
    episodes: Array<PlaylistEpisodeOutput>;
};

export type PlaylistEpisodeOutput = {
    position: number;
    episode_id: string;
};

export type PlaylistEpisodesOutput = {
    episodes: Array<PlaylistEpisodeWithExtrasOutput>;
    seasons: {
        [key: string]: SeasonOutput;
    };
    shows: {
        [key: string]: ShowPublic;
    };
    sources: {
        [key: string]: SourcePublic;
    };
    plugins: {
        [key: string]: PluginOutput;
    };
};

export type PlaylistEpisodeWithExtrasOutput = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    url?: (string | null);
    sort_order?: (number | null);
    description?: (string | null);
    image_url?: (string | null);
    episode_number?: (number | null);
    name?: (string | null);
    duration?: (number | null);
    release_date?: (string | null);
    air_date?: (string | null);
    id: string;
    season_id: string;
    position: number;
    watch_date?: (string | null);
    verified?: (boolean | null);
    episode_watch_id?: (string | null);
};

/**
 * Schema for returning a `Playlist`.
 */
export type PlaylistOutput = {
    name?: (string | null);
    visibility: Visibility;
    id: string;
    user_id: string;
    created_at: string;
    modified_at: string;
};

/**
 * Schema for updating a `Playlist`.
 */
export type PlaylistUpdate = {
    name?: (string | null);
    visibility?: (Visibility | null);
    episode_ids?: (Array<(string)> | null);
};

/**
 * Schema for creating a `Plugin`.
 */
export type PluginCreate = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    version?: (string | null);
    visibility: Visibility;
};

export type PluginImportURLInformation = {
    name: string;
    instructions: string;
};

export type PluginImportWatchHistoryInformation = {
    plugin_key: string;
    file_extension: string;
    instructions: string;
};

/**
 * Schema for returning a `Plugin`.
 */
export type PluginOutput = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    version?: (string | null);
    visibility: Visibility;
    id: string;
};

export type PluginSearchInformation = {
    plugin_key: string;
    name: string;
};

/**
 * Search result from a plugin.
 */
export type PluginSearchResult = {
    title: string;
    url: string;
    year?: (number | null);
    image_url?: (string | null);
    media_type?: (string | null);
    sources?: Array<PluginSearchResultSource>;
};

/**
 * Results from a search query.
 */
export type PluginSearchResults = {
    has_source_selection: boolean;
    results: Array<PluginSearchResult>;
};

/**
 * Source information for a search result.
 *
 * Used for plugins that support multiple sources.
 */
export type PluginSearchResultSource = {
    name: string;
    icon_url?: (string | null);
};

/**
 * Schema for returning a list of `Plugin`s.
 */
export type PluginsPublic = {
    data: Array<PluginOutput>;
    total_count: number;
    filtered_count: number;
    is_server_side: boolean;
};

/**
 * Schema for updating a `Plugin`.
 */
export type PluginUpdate = {
    key?: (string | null);
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    version?: (string | null);
    visibility?: (Visibility | null);
};

export type PluginURLMatch = {
    matched: boolean;
    plugin_key?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    username: string;
    is_verified?: boolean;
};

/**
 * Schema for creating a `Season`.
 */
export type SeasonCreate = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    sort_order?: (number | null);
    name?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
    season_number?: (number | null);
};

/**
 * Schema for returning a `Season`.
 */
export type SeasonOutput = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    sort_order?: (number | null);
    name?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
    season_number?: (number | null);
    show_id: string;
    id: string;
};

/**
 * Schema for returning a list of `Season`s.
 */
export type SeasonsPublic = {
    data: Array<SeasonOutput>;
    total_count: number;
    filtered_count: number;
    is_server_side: boolean;
};

/**
 * Schema for updating a `Season`.
 */
export type SeasonUpdate = {
    key?: (string | null);
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    sort_order?: (number | null);
    name?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
    season_number?: (number | null);
};

/**
 * Schema for creating a `Show`.
 */
export type ShowCreate = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    media_type?: (string | null);
    description?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
};

/**
 * Schema for returning a `Show`.
 */
export type ShowPublic = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    media_type?: (string | null);
    description?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
    source_id: string;
    id: string;
};

/**
 * Schema for returning a list of `Show`s.
 */
export type ShowsPublic = {
    data: Array<ShowPublic>;
    total_count: number;
    filtered_count: number;
    is_server_side: boolean;
};

/**
 * Schema for updating a `Show`.
 */
export type ShowUpdate = {
    key?: (string | null);
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    media_type?: (string | null);
    description?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
};

export type SortKeyInput = {
    model: 'episode' | 'season' | 'show' | 'source' | 'plugin';
    field: string;
    direction: 'ascending' | 'descending';
    order: 'sequential' | 'interleave' | 'randomize';
    aggregation?: ('max' | 'min' | 'avg' | null);
    days?: (number | null);
    recentlyAiredDate?: (string | null);
    fuzziness?: (number | null);
};

export type model = 'episode' | 'season' | 'show' | 'source' | 'plugin';

export type direction = 'ascending' | 'descending';

export type order = 'sequential' | 'interleave' | 'randomize';

export type SortOption = {
    id: string;
    desc?: boolean;
};

export type SortOptionOutput = {
    label: string;
    model: 'episode' | 'season' | 'show' | 'source' | 'plugin';
    field: string;
};

/**
 * Schema for creating a `Source`.
 */
export type SourceCreate = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    favicon_url?: (string | null);
    image_url?: (string | null);
};

/**
 * Schema for returning a `Source`.
 */
export type SourcePublic = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    favicon_url?: (string | null);
    image_url?: (string | null);
    plugin_id: string;
    id: string;
};

/**
 * Schema for returning a list of `Source`s.
 */
export type SourcesPublic = {
    data: Array<SourcePublic>;
    total_count: number;
    filtered_count: number;
    is_server_side: boolean;
};

/**
 * Schema for updating a `Source`.
 */
export type SourceUpdate = {
    key?: (string | null);
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    favicon_url?: (string | null);
    image_url?: (string | null);
};

export type StringFilterOption = {
    id: string;
    value: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Enum representing the status of a URL in the channel queue.
 */
export type URLStatus = 'Pending' | 'Failed' | 'Imported' | 'Importing';

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    username?: (string | null);
    server_side_threshold?: number;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    username?: (string | null);
    server_side_threshold?: number;
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    username?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    username?: (string | null);
    server_side_threshold?: number;
    password?: (string | null);
};

export type UserUpdateMe = {
    username?: (string | null);
    email?: (string | null);
    server_side_threshold?: (number | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Visibility level for `Channel`, `Plugin`, and `Playlist` records.
 */
export type Visibility = 'public' | 'unlisted' | 'private';

/**
 * Schema for creating a `Watch`.
 */
export type WatchCreate = {
    watch_date?: string;
    verified?: boolean;
};

export type WatchesListOutput = {
    watches: Array<WatchItem>;
    episodes: {
        [key: string]: EpisodeOutput;
    };
    seasons: {
        [key: string]: SeasonOutput;
    };
    shows: {
        [key: string]: ShowPublic;
    };
    sources: {
        [key: string]: SourcePublic;
    };
    plugins: {
        [key: string]: PluginOutput;
    };
};

export type WatchImportResult = {
    show: string;
    show_url: string;
    episode: string;
    episode_url: string;
};

export type WatchImportResults = {
    added: Array<WatchImportResult>;
    existing: Array<WatchImportResult>;
    skipped: Array<WatchImportResult>;
};

export type WatchItem = {
    watch_date: string;
    verified: boolean;
    id: string;
    episode_id: string;
};

/**
 * Schema for returning a `Watch`.
 */
export type WatchOutput = {
    watch_date: string;
    verified: boolean;
    id: string;
    episode_id: string;
    user_id: string;
};

/**
 * Schema for updating a `Watch`.
 */
export type WatchUpdate = {
    watch_date?: (string | null);
    verified?: (boolean | null);
};

export type WhitelistEntryInput = {
    id: string;
    marked: boolean;
    expires_at?: (string | null);
};

export type WhitelistEpisodeOutput = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    url?: (string | null);
    sort_order?: (number | null);
    description?: (string | null);
    image_url?: (string | null);
    episode_number?: (number | null);
    name?: (string | null);
    duration?: (number | null);
    release_date?: (string | null);
    air_date?: (string | null);
    id: string;
    season_id: string;
    filtered: boolean;
    expires_at?: (string | null);
};

export type WhitelistSeasonOutput = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    sort_order?: (number | null);
    name?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
    season_number?: (number | null);
    show_id: string;
    id: string;
    filtered: boolean;
};

export type WhitelistShowInput = {
    is_whitelist?: (boolean | null);
    seasons?: Array<WhitelistEntryInput>;
    episodes?: Array<WhitelistEntryInput>;
};

export type WhitelistShowOutput = {
    key: string;
    data_timestamp?: (string | null);
    update_at?: (string | null);
    deleted_at?: (string | null);
    extra?: (string | null);
    name?: (string | null);
    media_type?: (string | null);
    description?: (string | null);
    url?: (string | null);
    image_url?: (string | null);
    source_id: string;
    id: string;
    is_whitelist: boolean;
    seasons: Array<WhitelistSeasonOutput>;
    episodes: Array<WhitelistEpisodeOutput>;
};

export type ChannelsGetChannelsResponse = (Array<ChannelOutput>);

export type ChannelsCreateChannelData = {
    requestBody: ChannelCreate;
};

export type ChannelsCreateChannelResponse = (ChannelOutput);

export type ChannelsGetSortOptionsResponse = (Array<SortOptionOutput>);

export type ChannelsBulkImportQueueUrlsData = {
    requestBody: {
        [key: string]: Array<(string)>;
    };
};

export type ChannelsBulkImportQueueUrlsResponse = (Message);

export type ChannelsGetPublicChannelsData = {
    limit?: number;
    offset?: number;
};

export type ChannelsGetPublicChannelsResponse = (ChannelPublicListOutput);

export type ChannelsAdminListChannelsResponse = (Array<ChannelAdminOutput>);

export type ChannelsAdminListUserChannelsData = {
    userId: string;
};

export type ChannelsAdminListUserChannelsResponse = (Array<ChannelAdminOutput>);

export type ChannelsAdminUpdateChannelData = {
    channelId: string;
    requestBody: ChannelAdminUpdate;
};

export type ChannelsAdminUpdateChannelResponse = (ChannelAdminOutput);

export type ChannelsGetChannelData = {
    channelId: string;
};

export type ChannelsGetChannelResponse = (ChannelOutput);

export type ChannelsUpdateChannelData = {
    channelId: string;
    requestBody: ChannelUpdate;
};

export type ChannelsUpdateChannelResponse = (ChannelOutput);

export type ChannelsDeleteChannelData = {
    channelId: string;
};

export type ChannelsDeleteChannelResponse = (Message);

export type ChannelsGetChannelEpisodesData = {
    additionalChannels?: Array<(string)>;
    channelId: string;
    hidePartiallyWatched?: boolean;
    hideUnwatched?: boolean;
    hideWatched?: boolean;
    limit?: (number | null);
    maximumAirDateAbsolute?: (string | null);
    maximumAirDateRelative?: (number | null);
    maximumDuration?: (number | null);
    maximumReleaseDateAbsolute?: (string | null);
    maximumReleaseDateRelative?: (number | null);
    maximumWatchDateAbsolute?: (string | null);
    maximumWatchDateRelative?: (number | null);
    minimumAirDateAbsolute?: (string | null);
    minimumAirDateRelative?: (number | null);
    minimumDuration?: (number | null);
    minimumReleaseDateAbsolute?: (string | null);
    minimumReleaseDateRelative?: (number | null);
    newShowsCount?: (number | null);
    randomSeed?: number;
    sortBy?: Array<SortKeyInput>;
    sourceIds?: Array<(string)>;
    sourceIdsIsBlacklist?: boolean;
    startedShowsCount?: (number | null);
    totalShowsCount?: (number | null);
};

export type ChannelsGetChannelEpisodesResponse = (ChannelEpisodesOutput);

export type ChannelsGetChannelShowsData = {
    channelId: string;
};

export type ChannelsGetChannelShowsResponse = (ChannelShowsOutput);

export type ChannelsGetChannelSourcesData = {
    channelId: string;
};

export type ChannelsGetChannelSourcesResponse = (Array<SourcePublic>);

export type ChannelsGetChannelWhitelistData = {
    channelId: string;
    showId: string;
};

export type ChannelsGetChannelWhitelistResponse = (WhitelistShowOutput);

export type ChannelsUpdateChannelWhitelistData = {
    channelId: string;
    requestBody: WhitelistShowInput;
    showId: string;
};

export type ChannelsUpdateChannelWhitelistResponse = (WhitelistShowOutput);

export type ChannelsBlacklistChannelEpisodeData = {
    channelId: string;
    requestBody: BlacklistEpisodeInput;
};

export type ChannelsBlacklistChannelEpisodeResponse = (Message);

export type ChannelsUpdateChannelDefaultOrderData = {
    channelId: string;
    requestBody: ChannelOptions;
};

export type ChannelsUpdateChannelDefaultOrderResponse = (ChannelOutput);

export type ChannelsDeleteChannelShowData = {
    channelId: string;
    showId: string;
};

export type ChannelsDeleteChannelShowResponse = (Message);

export type ChannelsGetChannelQueueData = {
    channelId: string;
};

export type ChannelsGetChannelQueueResponse = (Array<ChannelQueueOutput>);

export type ChannelsCreateChannelQueueUrlsData = {
    channelId: string;
    requestBody: Array<(string)>;
};

export type ChannelsCreateChannelQueueUrlsResponse = (Array<ChannelQueueOutput>);

export type ChannelsDeleteChannelQueueUrlData = {
    channelId: string;
    urlId: string;
};

export type ChannelsDeleteChannelQueueUrlResponse = (Message);

export type ChannelsClearChannelCompletedQueueData = {
    channelId: string;
};

export type ChannelsClearChannelCompletedQueueResponse = (Message);

export type EpisodesGetEpisodesData = {
    dateFilterOptions?: string;
    filterOptions?: string;
    limit?: number;
    offset?: number;
    owner?: (MediaOwner | null);
    sortOptions?: string;
};

export type EpisodesGetEpisodesResponse = (EpisodesPublic);

export type EpisodesGetEpisodeData = {
    episodeId: string;
};

export type EpisodesGetEpisodeResponse = (EpisodeOutput);

export type EpisodesUpdateEpisodeData = {
    episodeId: string;
    requestBody: EpisodeUpdate;
};

export type EpisodesUpdateEpisodeResponse = (EpisodeOutput);

export type EpisodesDeleteEpisodeData = {
    episodeId: string;
};

export type EpisodesDeleteEpisodeResponse = (Message);

export type EpisodesCreateWatchData = {
    episodeId: string;
    requestBody: WatchCreate;
};

export type EpisodesCreateWatchResponse = (Array<WatchOutput>);

export type FilesGetFileData = {
    fileId: string;
};

export type FilesGetFileResponse = (FilePublic);

export type FilesUpdateFileData = {
    fileId: string;
    requestBody: FileUpdate;
};

export type FilesUpdateFileResponse = (FilePublic);

export type FilesDeleteFileData = {
    fileId: string;
};

export type FilesDeleteFileResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PlaylistsGetPlaylistsResponse = (Array<PlaylistOutput>);

export type PlaylistsCreatePlaylistData = {
    requestBody: PlaylistCreate;
};

export type PlaylistsCreatePlaylistResponse = (PlaylistDetailOutput);

export type PlaylistsGetPlaylistData = {
    playlistId: string;
};

export type PlaylistsGetPlaylistResponse = (PlaylistDetailOutput);

export type PlaylistsUpdatePlaylistData = {
    playlistId: string;
    requestBody: PlaylistUpdate;
};

export type PlaylistsUpdatePlaylistResponse = (PlaylistDetailOutput);

export type PlaylistsDeletePlaylistData = {
    playlistId: string;
};

export type PlaylistsDeletePlaylistResponse = (Message);

export type PlaylistsGetPlaylistEpisodesData = {
    playlistId: string;
};

export type PlaylistsGetPlaylistEpisodesResponse = (PlaylistEpisodesOutput);

export type PluginsImportWatchHistoryInformationResponse = (Array<PluginImportWatchHistoryInformation>);

export type PluginsImportUrlInformationResponse = (Array<PluginImportURLInformation>);

export type PluginsMatchUrlData = {
    url: string;
};

export type PluginsMatchUrlResponse = (PluginURLMatch);

export type PluginsSearchInformationResponse = (Array<PluginSearchInformation>);

export type PluginsSearchPluginData = {
    pluginKey: string;
    query: string;
};

export type PluginsSearchPluginResponse = (PluginSearchResults);

export type PluginsGetPluginsData = {
    dateFilterOptions?: string;
    filterOptions?: string;
    limit?: number;
    offset?: number;
    owner?: (MediaOwner | null);
    sortOptions?: string;
};

export type PluginsGetPluginsResponse = (PluginsPublic);

export type PluginsCreatePluginData = {
    requestBody: PluginCreate;
};

export type PluginsCreatePluginResponse = (PluginOutput);

export type PluginsGetPluginSourcesData = {
    dateFilterOptions?: string;
    filterOptions?: string;
    limit?: number;
    offset?: number;
    pluginId: string;
    sortOptions?: string;
};

export type PluginsGetPluginSourcesResponse = (SourcesPublic);

export type PluginsCreateSourceData = {
    pluginId: string;
    requestBody: SourceCreate;
};

export type PluginsCreateSourceResponse = (SourcePublic);

export type PluginsUpdatePluginData = {
    pluginId: string;
    requestBody: PluginUpdate;
};

export type PluginsUpdatePluginResponse = (PluginOutput);

export type PluginsDeletePluginData = {
    pluginId: string;
};

export type PluginsDeletePluginResponse = (Message);

export type PluginsGetPluginData = {
    pluginId: string;
};

export type PluginsGetPluginResponse = (PluginOutput);

export type PluginsGetPluginFilesData = {
    content?: (string | null);
    pluginId: string;
};

export type PluginsGetPluginFilesResponse = (Array<FileListPublic>);

export type PluginsCreateFileData = {
    pluginId: string;
    requestBody: FileCreate;
};

export type PluginsCreateFileResponse = (FilePublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SeasonsGetSeasonsData = {
    dateFilterOptions?: string;
    filterOptions?: string;
    limit?: number;
    offset?: number;
    owner?: (MediaOwner | null);
    sortOptions?: string;
};

export type SeasonsGetSeasonsResponse = (SeasonsPublic);

export type SeasonsGetSeasonData = {
    seasonId: string;
};

export type SeasonsGetSeasonResponse = (SeasonOutput);

export type SeasonsUpdateSeasonData = {
    requestBody: SeasonUpdate;
    seasonId: string;
};

export type SeasonsUpdateSeasonResponse = (SeasonOutput);

export type SeasonsDeleteSeasonData = {
    seasonId: string;
};

export type SeasonsDeleteSeasonResponse = (Message);

export type SeasonsCreateEpisodeData = {
    requestBody: EpisodeCreate;
    seasonId: string;
};

export type SeasonsCreateEpisodeResponse = (EpisodeOutput);

export type SeasonsGetEpisodesData = {
    dateFilterOptions?: string;
    filterOptions?: string;
    limit?: number;
    offset?: number;
    seasonId: string;
    sortOptions?: string;
};

export type SeasonsGetEpisodesResponse = (EpisodesPublic);

export type ShowsGetShowsData = {
    dateFilterOptions?: string;
    filterOptions?: string;
    limit?: number;
    offset?: number;
    owner?: (MediaOwner | null);
    sortOptions?: string;
};

export type ShowsGetShowsResponse = (ShowsPublic);

export type ShowsGetShowData = {
    showId: string;
};

export type ShowsGetShowResponse = (ShowPublic);

export type ShowsUpdateShowData = {
    requestBody: ShowUpdate;
    showId: string;
};

export type ShowsUpdateShowResponse = (ShowPublic);

export type ShowsDeleteShowData = {
    showId: string;
};

export type ShowsDeleteShowResponse = (Message);

export type ShowsCreateSeasonData = {
    requestBody: SeasonCreate;
    showId: string;
};

export type ShowsCreateSeasonResponse = (SeasonOutput);

export type ShowsGetSeasonsData = {
    dateFilterOptions?: string;
    filterOptions?: string;
    limit?: number;
    offset?: number;
    showId: string;
    sortOptions?: string;
};

export type ShowsGetSeasonsResponse = (SeasonsPublic);

export type SourcesGetSourcesData = {
    dateFilterOptions?: string;
    filterOptions?: string;
    limit?: number;
    offset?: number;
    owner?: (MediaOwner | null);
    sortOptions?: string;
};

export type SourcesGetSourcesResponse = (SourcesPublic);

export type SourcesGetSourceData = {
    sourceId: string;
};

export type SourcesGetSourceResponse = (SourcePublic);

export type SourcesUpdateSourceData = {
    requestBody: SourceUpdate;
    sourceId: string;
};

export type SourcesUpdateSourceResponse = (SourcePublic);

export type SourcesDeleteSourceData = {
    sourceId: string;
};

export type SourcesDeleteSourceResponse = (Message);

export type SourcesCreateShowData = {
    requestBody: ShowCreate;
    sourceId: string;
};

export type SourcesCreateShowResponse = (ShowPublic);

export type SourcesGetShowsData = {
    dateFilterOptions?: string;
    filterOptions?: string;
    limit?: number;
    offset?: number;
    sortOptions?: string;
    sourceId: string;
};

export type SourcesGetShowsResponse = (ShowsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WatchesGetWatchesResponse = (WatchesListOutput);

export type WatchesGetWatchData = {
    watchId: string;
};

export type WatchesGetWatchResponse = (WatchOutput);

export type WatchesUpdateWatchData = {
    requestBody: WatchUpdate;
    watchId: string;
};

export type WatchesUpdateWatchResponse = (Array<WatchOutput>);

export type WatchesDeleteWatchData = {
    watchId: string;
};

export type WatchesDeleteWatchResponse = (Message);

export type WatchesSyncWatchesResponse = (Message);

export type WatchesImportWatchHistoryData = {
    formData: Body_watches_import_watch_history;
    newOnly: boolean;
    pluginKey: string;
    verified: boolean;
};

export type WatchesImportWatchHistoryResponse = (WatchImportResults);