"""Improve channel indexes

Revision ID: 4fdff664024d
Revises: 62579186590b
Create Date: 2026-03-07 05:09:46.939204

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4fdff664024d'
down_revision = '62579186590b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
