"""replace snapshot with channel custom order

Revision ID: 5f58aa435435
Revises: a1b2c3d4e5f6
Create Date: 2026-07-02 01:18:31.680077

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f58aa435435'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channelsavedepisodeorder',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'episode_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ChannelSavedEpisodeOrder-channel_id-position-index', 'channelsavedepisodeorder', ['channel_id', 'position'], unique=False)
    op.create_index('ChannelSavedEpisodeOrder-episode_id-index', 'channelsavedepisodeorder', ['episode_id'], unique=False)
    op.drop_index(op.f('SnapshotEpisode-episode_id-index'), table_name='snapshotepisode')
    op.drop_table('snapshotepisode')
    op.drop_index(op.f('Snapshot-user_id-index'), table_name='snapshot')
    op.drop_table('snapshot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visibility', postgresql.ENUM('public', 'unlisted', 'private', name='visibility', create_type=False), autoincrement=False, nullable=False),
    sa.Column('anonymous', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('playlist_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_pkey')),
    sa.UniqueConstraint('id', name=op.f('playlist_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('Snapshot-user_id-index'), 'snapshot', ['user_id'], unique=False)
    op.create_table('snapshotepisode',
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('snapshot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('episode_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name=op.f('playlistepisode_episode_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], name=op.f('playlistepisode_playlist_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'position', name=op.f('playlistepisode_pkey')),
    sa.UniqueConstraint('id', name=op.f('playlistepisode_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('SnapshotEpisode-episode_id-index'), 'snapshotepisode', ['episode_id'], unique=False)
    op.drop_index('ChannelSavedEpisodeOrder-episode_id-index', table_name='channelsavedepisodeorder')
    op.drop_index('ChannelSavedEpisodeOrder-channel_id-position-index', table_name='channelsavedepisodeorder')
    op.drop_table('channelsavedepisodeorder')
    # ### end Alembic commands ###
