"""Add is_blacklist_only to channel show and expires_at to episode filter

Revision ID: 1ca97bd82157
Revises: f5813544368a
Create Date: 2026-06-25 19:45:38.712374

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1ca97bd82157'
down_revision = 'f5813544368a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channelepisodefilter', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('channelshow', sa.Column('is_blacklist_only', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('channelshow', 'is_blacklist_only', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channelshow', 'is_blacklist_only')
    op.drop_column('channelepisodefilter', 'expires_at')
    # ### end Alembic commands ###
