"""Update indexes

Revision ID: f5813544368a
Revises: 51c2001ab376
Create Date: 2026-05-19 14:22:25.978633

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "f5813544368a"
down_revision = "51c2001ab376"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("Plugin-name-index", "plugin", ["name"], unique=False)
    op.create_index("Plugin-visibility-index", "plugin", ["visibility"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("Plugin-visibility-index", table_name="plugin")
    op.drop_index("Plugin-name-index", table_name="plugin")
    # ### end Alembic commands ###
