"""rename channel.public to is_public

Revision ID: 3f3a4fef83b2
Revises: 80ad1777275c
Create Date: 2026-04-30 22:27:36.137932

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3f3a4fef83b2'
down_revision = '80ad1777275c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'public', new_column_name='is_public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'is_public', new_column_name='public')
    # ### end Alembic commands ###
