"""watch_identifier is a column like any other

`watch_identifier` was generated by the database from `plugin_key || ' ' || key`,
which meant `episode` carried `plugin_key` for no other reason: a generated column
can only be built from columns of its own row, so the plugin's key had to be
copied onto every episode to be reachable from there.

It is written by `Episode.upsert` now, off the season being upserted onto, so
`plugin_key` has nothing left to do.

`DROP EXPRESSION` keeps every value already stored, so nothing is recomputed and
no watch is left pointing at an identifier that moved.

Revision ID: c3d9e5a71f42
Revises: b7e1f4a92c58
Create Date: 2026-08-15 16:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c3d9e5a71f42"
down_revision = "b7e1f4a92c58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE episode ALTER COLUMN watch_identifier DROP EXPRESSION")
    op.execute("ALTER TABLE episode DROP COLUMN plugin_key")


def downgrade() -> None:
    # The plugin's key is the first word of the identifier, which is what put it
    # there, so the column it was copied from is read back out of it.
    op.execute("ALTER TABLE episode ADD COLUMN plugin_key text")
    op.execute("UPDATE episode SET plugin_key = split_part(watch_identifier, ' ', 1)")
    op.execute("ALTER TABLE episode ALTER COLUMN plugin_key SET NOT NULL")
    op.execute("ALTER TABLE episode DROP COLUMN watch_identifier")
    op.execute(
        "ALTER TABLE episode ADD COLUMN watch_identifier text NOT NULL "
        "GENERATED ALWAYS AS (plugin_key || ' ' || \"key\") STORED",
    )
    op.execute(
        'CREATE INDEX "Episode-watch_identifier-index" ON episode (watch_identifier)',
    )
