"""add channel comments

Revision ID: 1b42a629d2f6
Revises: 032f94e16559
Create Date: 2026-07-30 04:23:25.371400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1b42a629d2f6'
down_revision = '032f94e16559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint('comment_id_key', 'comment', ['id'])
    op.create_index('Comment-channel_id-index', 'comment', ['channel_id'], unique=False)
    op.create_index('Comment-parent_comment_id-index', 'comment', ['parent_comment_id'], unique=False)
    op.create_index('Comment-user_id-index', 'comment', ['user_id'], unique=False)
    op.create_table('commentnotification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('CommentNotification-comment_id-index', 'commentnotification', ['comment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('CommentNotification-comment_id-index', table_name='commentnotification')
    op.drop_table('commentnotification')
    op.drop_index('Comment-user_id-index', table_name='comment')
    op.drop_index('Comment-parent_comment_id-index', table_name='comment')
    op.drop_index('Comment-channel_id-index', table_name='comment')
    op.drop_constraint('comment_id_key', 'comment', type_='unique')
    op.drop_table('comment')
    # ### end Alembic commands ###
