"""add channel order and combined channel tables

Revision ID: d9af2e3b8dcf
Revises: 5f58aa435435
Create Date: 2026-07-15 20:30:38.644538

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "d9af2e3b8dcf"
down_revision = "5f58aa435435"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channelorder",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "visibility",
            postgresql.ENUM(
                "public", "unlisted", "private", name="visibility", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("anonymous", sa.Boolean(), nullable=False),
        sa.Column("config", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "ChannelOrder-user_id-index", "channelorder", ["user_id"], unique=False
    )
    op.create_table(
        "channelcombinedchannel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("combined_channel_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["channel_id"], ["channel.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["combined_channel_id"], ["channel.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("channel_id", "combined_channel_id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        "ChannelCombinedChannel-combined_channel_id-index",
        "channelcombinedchannel",
        ["combined_channel_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ChannelCombinedChannel-combined_channel_id-index",
        table_name="channelcombinedchannel",
    )
    op.drop_table("channelcombinedchannel")
    op.drop_index("ChannelOrder-user_id-index", table_name="channelorder")
    op.drop_table("channelorder")
    # ### end Alembic commands ###
