"""Update keys

Revision ID: e7911746fbdc
Revises: 8a188d164bfc
Create Date: 2026-03-04 01:06:56.403999

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e7911746fbdc'
down_revision = '8a188d164bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file', ['id'])
    op.create_unique_constraint(None, 'plugin', ['id'])
    op.create_index('Source-deleted_at-index', 'source', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('Source-deleted_at-index', table_name='source')
    op.drop_constraint(None, 'plugin', type_='unique')
    op.drop_constraint(None, 'file', type_='unique')
    # ### end Alembic commands ###
