"""require unique username

Revision ID: bbc24e1b5276
Revises: 1b42a629d2f6
Create Date: 2026-07-30 04:38:13.503068

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bbc24e1b5276'
down_revision = '1b42a629d2f6'
branch_labels = None
depends_on = None


def upgrade():
    # Users created before a username was required have none, so give them the local
    # part of their email address to start from.
    op.execute(
        """
        UPDATE "user"
        SET username = split_part(email, '@', 1)
        WHERE username IS NULL OR username = ''
        """
    )
    # The backfill above can collide, and usernames were never unique before, so keep
    # the oldest row's username and suffix every other one with part of its id.
    op.execute(
        """
        WITH ranked AS (
            SELECT
                id,
                row_number() OVER (
                    PARTITION BY username ORDER BY created_at NULLS LAST, id
                ) AS position
            FROM "user"
        )
        UPDATE "user" AS target
        SET username = target.username || '-' || left(target.id::text, 8)
        FROM ranked
        WHERE ranked.id = target.id AND ranked.position > 1
        """
    )
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
