"""index watch episode_identifier

Revision ID: 032f94e16559
Revises: e9d773710769
Create Date: 2026-07-29 21:40:59.213195

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "032f94e16559"
down_revision = "e9d773710769"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "Watch-episode_identifier-index", "watch", ["episode_identifier"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("Watch-episode_identifier-index", table_name="watch")
    # ### end Alembic commands ###
