"""New initial data structure.

Revision ID: 19da7f8c7cb3
Revises: fe56fa70289e
Create Date: 2026-02-22 13:41:15.088634

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19da7f8c7cb3'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('id')
    )
    op.create_index('Plugin-deleted_at-index', 'plugin', ['deleted_at'], unique=False)
    op.create_table('channel',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('default_order', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('file',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plugin_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plugin_id', 'key'),
    sa.UniqueConstraint('id')
    )
    op.create_table('source',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('favicon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plugin_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plugin_id', 'key'),
    sa.UniqueConstraint('id')
    )
    op.create_index('Source-name-index', 'source', ['name'], unique=False)
    op.create_table('channelqueue',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FAILED', 'IMPORTED', 'IMPORTING', name='urlstatus'), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'url'),
    sa.UniqueConstraint('id')
    )
    op.create_table('show',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'key'),
    sa.UniqueConstraint('id')
    )
    op.create_index('Show-deleted_at-index', 'show', ['deleted_at'], unique=False)
    op.create_index('Show-media_type-index', 'show', ['media_type'], unique=False)
    op.create_index('Show-name-index', 'show', ['name'], unique=False)
    op.create_table('channelshow',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.Column('white_list_mode', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'show_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ChannelShow-channel_id-index', 'channelshow', ['channel_id'], unique=False)
    op.create_index('ChannelShow-show_id-index', 'channelshow', ['show_id'], unique=False)
    op.create_table('season',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('show_id', 'key'),
    sa.UniqueConstraint('id')
    )
    op.create_index('Season-deleted_at-index', 'season', ['deleted_at'], unique=False)
    op.create_index('Season-name-index', 'season', ['name'], unique=False)
    op.create_index('Season-season_number-index', 'season', ['season_number'], unique=False)
    op.create_index('Season-sort_order-index', 'season', ['sort_order'], unique=False)
    op.create_table('channelseasonwhitelist',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('channel_show_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['channel_show_id'], ['channelshow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_show_id', 'season_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ChannelSeasonWhiteList-channel_show_id-index', 'channelseasonwhitelist', ['channel_show_id'], unique=False)
    op.create_index('ChannelSeasonWhiteList-season_id-index', 'channelseasonwhitelist', ['season_id'], unique=False)
    op.create_table('episode',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('season_id', 'key'),
    sa.UniqueConstraint('id')
    )
    op.create_index('Episode-air_date-index', 'episode', ['air_date'], unique=False)
    op.create_index('Episode-deleted_at-index', 'episode', ['deleted_at'], unique=False)
    op.create_index('Episode-duration-index', 'episode', ['duration'], unique=False)
    op.create_index('Episode-episode_number-index', 'episode', ['episode_number'], unique=False)
    op.create_index('Episode-name-index', 'episode', ['name'], unique=False)
    op.create_index('Episode-release_date-index', 'episode', ['release_date'], unique=False)
    op.create_index('Episode-sort_order-index', 'episode', ['sort_order'], unique=False)
    op.create_table('channelepisodewhitelist',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('channel_show_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['channel_show_id'], ['channelshow.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_show_id', 'episode_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ChannelEpisodeWhiteList-channel_show_id-index', 'channelepisodewhitelist', ['channel_show_id'], unique=False)
    op.create_index('ChannelEpisodeWhiteList-episode_id-index', 'channelepisodewhitelist', ['episode_id'], unique=False)
    op.create_table('episodewatch',
    sa.Column('watch_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'episode_id', 'watch_date'),
    sa.UniqueConstraint('id')
    )
    op.create_index('EpisodeWatch-user_id-episode_id-index', 'episodewatch', ['user_id', 'episode_id'], unique=False)
    op.create_index('EpisodeWatch-user_id-verified-index', 'episodewatch', ['user_id', 'verified'], unique=False)
    op.create_index('EpisodeWatch-watch_date-index', 'episodewatch', ['watch_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('EpisodeWatch-watch_date-index', table_name='episodewatch')
    op.drop_index('EpisodeWatch-user_id-verified-index', table_name='episodewatch')
    op.drop_index('EpisodeWatch-user_id-episode_id-index', table_name='episodewatch')
    op.drop_table('episodewatch')
    op.drop_index('ChannelEpisodeWhiteList-episode_id-index', table_name='channelepisodewhitelist')
    op.drop_index('ChannelEpisodeWhiteList-channel_show_id-index', table_name='channelepisodewhitelist')
    op.drop_table('channelepisodewhitelist')
    op.drop_index('Episode-sort_order-index', table_name='episode')
    op.drop_index('Episode-release_date-index', table_name='episode')
    op.drop_index('Episode-name-index', table_name='episode')
    op.drop_index('Episode-episode_number-index', table_name='episode')
    op.drop_index('Episode-duration-index', table_name='episode')
    op.drop_index('Episode-deleted_at-index', table_name='episode')
    op.drop_index('Episode-air_date-index', table_name='episode')
    op.drop_table('episode')
    op.drop_index('ChannelSeasonWhiteList-season_id-index', table_name='channelseasonwhitelist')
    op.drop_index('ChannelSeasonWhiteList-channel_show_id-index', table_name='channelseasonwhitelist')
    op.drop_table('channelseasonwhitelist')
    op.drop_index('Season-sort_order-index', table_name='season')
    op.drop_index('Season-season_number-index', table_name='season')
    op.drop_index('Season-name-index', table_name='season')
    op.drop_index('Season-deleted_at-index', table_name='season')
    op.drop_table('season')
    op.drop_index('ChannelShow-show_id-index', table_name='channelshow')
    op.drop_index('ChannelShow-channel_id-index', table_name='channelshow')
    op.drop_table('channelshow')
    op.drop_index('Show-name-index', table_name='show')
    op.drop_index('Show-media_type-index', table_name='show')
    op.drop_index('Show-deleted_at-index', table_name='show')
    op.drop_table('show')
    op.drop_table('channelqueue')
    op.drop_index('Source-name-index', table_name='source')
    op.drop_table('source')
    op.drop_table('file')
    op.drop_table('channel')
    op.drop_index('Plugin-deleted_at-index', table_name='plugin')
    op.drop_table('plugin')
    # ### end Alembic commands ###
