/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWatchesRouteImport } from './routes/_layout/watches'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutPluginIndexRouteImport } from './routes/_layout/plugin.index'
import { Route as LayoutChannelsIndexRouteImport } from './routes/_layout/channels.index'
import { Route as LayoutWatchesImportRouteImport } from './routes/_layout/watches_.import'
import { Route as LayoutSourceSourceKeyRouteImport } from './routes/_layout/source.$sourceKey'
import { Route as LayoutShowShowKeyRouteImport } from './routes/_layout/show.$showKey'
import { Route as LayoutSeasonSeasonKeyRouteImport } from './routes/_layout/season.$seasonKey'
import { Route as LayoutPluginPluginKeyRouteImport } from './routes/_layout/plugin.$pluginKey'
import { Route as LayoutChannelsChannelIdRouteImport } from './routes/_layout/channels.$channelId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWatchesRoute = LayoutWatchesRouteImport.update({
  id: '/watches',
  path: '/watches',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPluginIndexRoute = LayoutPluginIndexRouteImport.update({
  id: '/plugin/',
  path: '/plugin/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChannelsIndexRoute = LayoutChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWatchesImportRoute = LayoutWatchesImportRouteImport.update({
  id: '/watches_/import',
  path: '/watches/import',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSourceSourceKeyRoute = LayoutSourceSourceKeyRouteImport.update({
  id: '/source/$sourceKey',
  path: '/source/$sourceKey',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutShowShowKeyRoute = LayoutShowShowKeyRouteImport.update({
  id: '/show/$showKey',
  path: '/show/$showKey',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSeasonSeasonKeyRoute = LayoutSeasonSeasonKeyRouteImport.update({
  id: '/season/$seasonKey',
  path: '/season/$seasonKey',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPluginPluginKeyRoute = LayoutPluginPluginKeyRouteImport.update({
  id: '/plugin/$pluginKey',
  path: '/plugin/$pluginKey',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChannelsChannelIdRoute = LayoutChannelsChannelIdRouteImport.update({
  id: '/channels/$channelId',
  path: '/channels/$channelId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/watches': typeof LayoutWatchesRoute
  '/channels/$channelId': typeof LayoutChannelsChannelIdRoute
  '/plugin/$pluginKey': typeof LayoutPluginPluginKeyRoute
  '/season/$seasonKey': typeof LayoutSeasonSeasonKeyRoute
  '/show/$showKey': typeof LayoutShowShowKeyRoute
  '/source/$sourceKey': typeof LayoutSourceSourceKeyRoute
  '/watches/import': typeof LayoutWatchesImportRoute
  '/channels/': typeof LayoutChannelsIndexRoute
  '/plugin/': typeof LayoutPluginIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/settings': typeof LayoutSettingsRoute
  '/watches': typeof LayoutWatchesRoute
  '/': typeof LayoutIndexRoute
  '/channels/$channelId': typeof LayoutChannelsChannelIdRoute
  '/plugin/$pluginKey': typeof LayoutPluginPluginKeyRoute
  '/season/$seasonKey': typeof LayoutSeasonSeasonKeyRoute
  '/show/$showKey': typeof LayoutShowShowKeyRoute
  '/source/$sourceKey': typeof LayoutSourceSourceKeyRoute
  '/watches/import': typeof LayoutWatchesImportRoute
  '/channels': typeof LayoutChannelsIndexRoute
  '/plugin': typeof LayoutPluginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/watches': typeof LayoutWatchesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/channels/$channelId': typeof LayoutChannelsChannelIdRoute
  '/_layout/plugin/$pluginKey': typeof LayoutPluginPluginKeyRoute
  '/_layout/season/$seasonKey': typeof LayoutSeasonSeasonKeyRoute
  '/_layout/show/$showKey': typeof LayoutShowShowKeyRoute
  '/_layout/source/$sourceKey': typeof LayoutSourceSourceKeyRoute
  '/_layout/watches_/import': typeof LayoutWatchesImportRoute
  '/_layout/channels/': typeof LayoutChannelsIndexRoute
  '/_layout/plugin/': typeof LayoutPluginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/watches'
    | '/channels/$channelId'
    | '/plugin/$pluginKey'
    | '/season/$seasonKey'
    | '/show/$showKey'
    | '/source/$sourceKey'
    | '/watches/import'
    | '/channels/'
    | '/plugin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/watches'
    | '/'
    | '/channels/$channelId'
    | '/plugin/$pluginKey'
    | '/season/$seasonKey'
    | '/show/$showKey'
    | '/source/$sourceKey'
    | '/watches/import'
    | '/channels'
    | '/plugin'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/dashboard'
    | '/_layout/settings'
    | '/_layout/watches'
    | '/_layout/'
    | '/_layout/channels/$channelId'
    | '/_layout/plugin/$pluginKey'
    | '/_layout/season/$seasonKey'
    | '/_layout/show/$showKey'
    | '/_layout/source/$sourceKey'
    | '/_layout/watches_/import'
    | '/_layout/channels/'
    | '/_layout/plugin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/watches': {
      id: '/_layout/watches'
      path: '/watches'
      fullPath: '/watches'
      preLoaderRoute: typeof LayoutWatchesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plugin/': {
      id: '/_layout/plugin/'
      path: '/plugin'
      fullPath: '/plugin/'
      preLoaderRoute: typeof LayoutPluginIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/channels/': {
      id: '/_layout/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof LayoutChannelsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/watches_/import': {
      id: '/_layout/watches_/import'
      path: '/watches/import'
      fullPath: '/watches/import'
      preLoaderRoute: typeof LayoutWatchesImportRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/source/$sourceKey': {
      id: '/_layout/source/$sourceKey'
      path: '/source/$sourceKey'
      fullPath: '/source/$sourceKey'
      preLoaderRoute: typeof LayoutSourceSourceKeyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/show/$showKey': {
      id: '/_layout/show/$showKey'
      path: '/show/$showKey'
      fullPath: '/show/$showKey'
      preLoaderRoute: typeof LayoutShowShowKeyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/season/$seasonKey': {
      id: '/_layout/season/$seasonKey'
      path: '/season/$seasonKey'
      fullPath: '/season/$seasonKey'
      preLoaderRoute: typeof LayoutSeasonSeasonKeyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plugin/$pluginKey': {
      id: '/_layout/plugin/$pluginKey'
      path: '/plugin/$pluginKey'
      fullPath: '/plugin/$pluginKey'
      preLoaderRoute: typeof LayoutPluginPluginKeyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/channels/$channelId': {
      id: '/_layout/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof LayoutChannelsChannelIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWatchesRoute: typeof LayoutWatchesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutChannelsChannelIdRoute: typeof LayoutChannelsChannelIdRoute
  LayoutPluginPluginKeyRoute: typeof LayoutPluginPluginKeyRoute
  LayoutSeasonSeasonKeyRoute: typeof LayoutSeasonSeasonKeyRoute
  LayoutShowShowKeyRoute: typeof LayoutShowShowKeyRoute
  LayoutSourceSourceKeyRoute: typeof LayoutSourceSourceKeyRoute
  LayoutWatchesImportRoute: typeof LayoutWatchesImportRoute
  LayoutChannelsIndexRoute: typeof LayoutChannelsIndexRoute
  LayoutPluginIndexRoute: typeof LayoutPluginIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWatchesRoute: LayoutWatchesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutChannelsChannelIdRoute: LayoutChannelsChannelIdRoute,
  LayoutPluginPluginKeyRoute: LayoutPluginPluginKeyRoute,
  LayoutSeasonSeasonKeyRoute: LayoutSeasonSeasonKeyRoute,
  LayoutShowShowKeyRoute: LayoutShowShowKeyRoute,
  LayoutSourceSourceKeyRoute: LayoutSourceSourceKeyRoute,
  LayoutWatchesImportRoute: LayoutWatchesImportRoute,
  LayoutChannelsIndexRoute: LayoutChannelsIndexRoute,
  LayoutPluginIndexRoute: LayoutPluginIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
